{
  description = "Cosmonaut Launcher – start/create GitHub Codespaces and open them in Zed";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    {
      homeManagerModules.default = import ./modules/home-manager.nix self;
      homeManagerModules.cosmonaut = import ./modules/home-manager.nix self;
      # Backwards compatibility alias.
      homeManagerModules.codespace-zed = import ./modules/home-manager.nix self;
    }
    //
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        cosmonaut = pkgs.buildGoModule {
          pname = "cosmonaut";
          version = "0.3.0";
          src = ./.;

          vendorHash = "sha256-Hc22uW6Eq1tY567WipjS8GCPWNJcT9Db5Wpovs/MAdU=";

          env.CGO_ENABLED = 1;

          nativeBuildInputs = [
            pkgs.makeWrapper
            pkgs.installShellFiles
            pkgs.pkg-config
          ] ++ pkgs.lib.optionals pkgs.stdenv.isLinux [
            pkgs.xvfb-run
          ];

          buildInputs = pkgs.lib.optionals pkgs.stdenv.isDarwin [
            pkgs.apple-sdk
          ] ++ pkgs.lib.optionals pkgs.stdenv.isLinux [
            pkgs.gtk3
            pkgs.libappindicator-gtk3
            # Fyne / GLFW dependencies
            pkgs.libGL
            pkgs.xorg.libX11
            pkgs.xorg.libXcursor
            pkgs.xorg.libXi
            pkgs.xorg.libXinerama
            pkgs.xorg.libXrandr
            pkgs.xorg.libXxf86vm
            pkgs.xorg.libXext
            pkgs.xorg.libXfixes
          ];

          postInstall = ''
            wrapProgram $out/bin/cosmonaut \
              --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.gh ]}

            # Shell completions (generated by cobra).
            # On Linux, xvfb-run is needed because golang.design/x/hotkey
            # initializes X11 on import.
            completionCmd="$out/bin/cosmonaut"
            if [[ "$(uname)" == "Linux" ]]; then
              completionCmd="xvfb-run $completionCmd"
            fi
            installShellCompletion --cmd cosmonaut \
              --bash <($completionCmd completion bash) \
              --zsh <($completionCmd completion zsh) \
              --fish <($completionCmd completion fish)

            # Dist files (example config, systemd service).
            install -Dm644 $src/dist/cosmonaut.config.example.json $out/share/cosmonaut/cosmonaut.config.example.json
            install -Dm644 $src/dist/cosmonaut.service $out/share/cosmonaut/cosmonaut.service
          '' + pkgs.lib.optionalString pkgs.stdenv.isDarwin ''
            # macOS .app bundle: gives the binary a dock icon, proper
            # app lifecycle, and allows launchd to manage it correctly.
            # Files must be real copies (not symlinks into /nix/store)
            # or Gatekeeper rejects the bundle as damaged.
            mkdir -p "$out/Applications/Cosmonaut.app/Contents/MacOS"
            mkdir -p "$out/Applications/Cosmonaut.app/Contents/Resources"
            cp $src/dist/Info.plist "$out/Applications/Cosmonaut.app/Contents/Info.plist"
            cp $src/assets/logo.icns "$out/Applications/Cosmonaut.app/Contents/Resources/icon.icns"
            # Copy the real Go binary (not the nix wrapper) into the app
            # bundle. The wrapper does exec -a which replaces the process
            # name with .cosmonaut-wrapped, breaking macOS bundle
            # identity (dock icon, app name). The Go binary's enrichPath()
            # discovers gh via the user's login shell PATH, so the nix
            # wrapper's PATH injection is not needed here.
            cp $out/bin/.cosmonaut-wrapped "$out/Applications/Cosmonaut.app/Contents/MacOS/cosmonaut"
          '';

          meta = with pkgs.lib; {
            description = "CLI for starting GitHub Codespaces and opening them in Zed";
            license = licenses.mit;
            mainProgram = "cosmonaut";
          };
        };
      in
      {
        packages = {
          default = cosmonaut;
          cosmonaut = cosmonaut;
        }
        # Linux: release tarball + AppImage
        // pkgs.lib.optionalAttrs pkgs.stdenv.isLinux {
          release =
            let
              pkg = cosmonaut;
              arch = if system == "x86_64-linux" then "amd64" else "arm64";
            in
            pkgs.runCommand "cosmonaut-${arch}.tar.gz"
              { nativeBuildInputs = [ pkgs.gzip ]; }
              ''
                # Ship the real Go binary (.cosmonaut-wrapped), not the nix
                # wrapper at bin/cosmonaut: that wrapper hardcodes /nix/store
                # paths and is unusable outside the build sandbox. Users need
                # gh on their own PATH, same as any standalone distribution.
                mkdir -p cosmonaut
                cp ${pkg}/bin/.cosmonaut-wrapped cosmonaut/cosmonaut
                chmod +w cosmonaut/cosmonaut
                cp ${./dist/cosmonaut.config.example.json} cosmonaut/
                cp ${./dist/cosmonaut.service} cosmonaut/
                tar -czvf $out -C . cosmonaut
              '';

          appimage =
            let
              pkg = cosmonaut;
              arch = if system == "x86_64-linux" then "x86_64" else "aarch64";

              appimageRuntime = pkgs.fetchurl (if system == "x86_64-linux" then {
                url = "https://github.com/AppImage/type2-runtime/releases/download/20251108/runtime-x86_64";
                hash = "sha256-L8qLRDySUQ8Ug6iD9gBhrQm0a5eLJjHIB82HOkfsJg0=";
              } else {
                url = "https://github.com/AppImage/type2-runtime/releases/download/20251108/runtime-aarch64";
                hash = "sha256-AMvfz5F8xsD/bTNH1Z4Moff0Wm3xpCig1tinhmTYdEQ=";
              });

              libPath = pkgs.lib.makeLibraryPath (with pkgs; [
                glib gtk3 libayatana-appindicator pango cairo gdk-pixbuf atk
                harfbuzz fontconfig freetype
                xorg.libX11 xorg.libXcursor xorg.libXrandr xorg.libXi
                xorg.libXext xorg.libXrender xorg.libXfixes
                xorg.libXcomposite xorg.libXdamage xorg.libxcb
                libxkbcommon wayland
              ]);
            in
            pkgs.runCommand "cosmonaut-${arch}.AppImage"
              { nativeBuildInputs = with pkgs; [ squashfsTools ]; }
              ''
                mkdir -p AppDir/usr/bin
                mkdir -p AppDir/usr/share/applications

                cp ${pkg}/bin/.cosmonaut-wrapped AppDir/usr/bin/cosmonaut
                chmod +w AppDir/usr/bin/*

                cat > AppDir/cosmonaut.desktop << 'DESKTOP'
                [Desktop Entry]
                Type=Application
                Name=cosmonaut
                Exec=cosmonaut applet
                Icon=cosmonaut
                Categories=Development;
                DESKTOP
                cp AppDir/cosmonaut.desktop AppDir/usr/share/applications/

                cat > AppDir/AppRun << 'APPRUN'
                #!/bin/bash
                set -e
                SELF=$(readlink -f "$0")
                APPDIR=''${SELF%/*}
                export LD_LIBRARY_PATH="LIBPATH:''${LD_LIBRARY_PATH}"
                export PATH="''${APPDIR}/usr/bin:''${PATH}"
                exec "''${APPDIR}/usr/bin/cosmonaut" "$@"
                APPRUN
                sed -i "s|LIBPATH|${libPath}|g" AppDir/AppRun
                chmod +x AppDir/AppRun

                mksquashfs AppDir appimage.squashfs -root-owned -noappend -comp zstd -quiet -no-progress
                cat ${appimageRuntime} appimage.squashfs > $out
                chmod +x $out
              '';
        };

        # The Darwin DMG is assembled by .github/workflows/release.yml
        # from the default package, not via a dedicated flake output,
        # so that the shipped binary is the raw .cosmonaut-wrapped file
        # instead of a nix wrapper referencing /nix/store paths.

        devShells.default = pkgs.mkShell {
          packages = [
            pkgs.go
            pkgs.gopls
            pkgs.gh
            pkgs.pkg-config
          ] ++ pkgs.lib.optionals pkgs.stdenv.isDarwin [
            pkgs.apple-sdk
          ] ++ pkgs.lib.optionals pkgs.stdenv.isLinux [
            pkgs.gtk3
            pkgs.libappindicator-gtk3
            pkgs.libGL
            pkgs.xorg.libX11
            pkgs.xorg.libXcursor
            pkgs.xorg.libXi
            pkgs.xorg.libXinerama
            pkgs.xorg.libXrandr
            pkgs.xorg.libXxf86vm
            pkgs.xorg.libXext
            pkgs.xorg.libXfixes
          ];
        };
      }
    );
}
