{
  description = "Cosmonaut Launcher – start/create GitHub Codespaces and open them in Zed";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    # nix-appimage produces a real, portable AppImage by bundling the full
    # closure into the squashfs and mounting it via user namespaces, so the
    # binary's /nix/store interpreter and RUNPATH resolve at runtime on any
    # Linux box. Replaces the previous hand-rolled AppRun that just exported
    # LD_LIBRARY_PATH to host /nix/store paths.
    nix-appimage = {
      url = "github:ralismark/nix-appimage";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flake-utils.follows = "flake-utils";
    };
  };

  outputs = { self, nixpkgs, flake-utils, nix-appimage }:
    {
      homeManagerModules.default = import ./modules/home-manager.nix self;
      homeManagerModules.cosmonaut = import ./modules/home-manager.nix self;
      # Backwards compatibility alias.
      homeManagerModules.codespace-zed = import ./modules/home-manager.nix self;
    }
    //
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        cosmonaut = pkgs.buildGoModule {
          pname = "cosmonaut";
          version = "0.3.0";
          src = ./.;

          vendorHash = "sha256-Hc22uW6Eq1tY567WipjS8GCPWNJcT9Db5Wpovs/MAdU=";

          env.CGO_ENABLED = 1;

          # netgo selects the pure-Go DNS resolver. CGO stays on for Fyne
          # (Cocoa/OpenGL via -framework, no dylib path embedding). On
          # darwin this does NOT drop the libresolv dylib link — Go
          # stdlib's internal/syscall/unix/net_darwin.go emits
          # //go:cgo_ldflag "-lresolv" unconditionally, so the linker
          # bakes nixpkgs's libresolv path into LC_LOAD_DYLIB regardless.
          # The DMG build in .github/workflows/release.yml rewrites that
          # load command to /usr/lib/libresolv.9.dylib via install_name_tool.
          tags = [ "netgo" ];

          nativeBuildInputs = [
            pkgs.makeWrapper
            pkgs.installShellFiles
            pkgs.pkg-config
          ] ++ pkgs.lib.optionals pkgs.stdenv.isLinux [
            pkgs.xvfb-run
          ];

          buildInputs = pkgs.lib.optionals pkgs.stdenv.isDarwin [
            pkgs.apple-sdk
          ] ++ pkgs.lib.optionals pkgs.stdenv.isLinux [
            pkgs.gtk3
            pkgs.libappindicator-gtk3
            # Fyne / GLFW dependencies
            pkgs.libGL
            pkgs.xorg.libX11
            pkgs.xorg.libXcursor
            pkgs.xorg.libXi
            pkgs.xorg.libXinerama
            pkgs.xorg.libXrandr
            pkgs.xorg.libXxf86vm
            pkgs.xorg.libXext
            pkgs.xorg.libXfixes
          ];

          postInstall = ''
            wrapProgram $out/bin/cosmonaut \
              --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.gh ]}

            # Shell completions (generated by cobra).
            # On Linux, xvfb-run is needed because golang.design/x/hotkey
            # initializes X11 on import.
            completionCmd="$out/bin/cosmonaut"
            if [[ "$(uname)" == "Linux" ]]; then
              completionCmd="xvfb-run $completionCmd"
            fi
            installShellCompletion --cmd cosmonaut \
              --bash <($completionCmd completion bash) \
              --zsh <($completionCmd completion zsh) \
              --fish <($completionCmd completion fish)

            # Dist files (example config, systemd service).
            install -Dm644 $src/dist/cosmonaut.config.example.json $out/share/cosmonaut/cosmonaut.config.example.json
            install -Dm644 $src/dist/cosmonaut.service $out/share/cosmonaut/cosmonaut.service
          '' + pkgs.lib.optionalString pkgs.stdenv.isDarwin ''
            # macOS .app bundle: gives the binary a dock icon, proper
            # app lifecycle, and allows launchd to manage it correctly.
            # Files must be real copies (not symlinks into /nix/store)
            # or Gatekeeper rejects the bundle as damaged.
            mkdir -p "$out/Applications/Cosmonaut.app/Contents/MacOS"
            mkdir -p "$out/Applications/Cosmonaut.app/Contents/Resources"
            cp $src/dist/Info.plist "$out/Applications/Cosmonaut.app/Contents/Info.plist"
            cp $src/assets/logo.icns "$out/Applications/Cosmonaut.app/Contents/Resources/icon.icns"
            # Copy the real Go binary (not the nix wrapper) into the app
            # bundle. The wrapper does exec -a which replaces the process
            # name with .cosmonaut-wrapped, breaking macOS bundle
            # identity (dock icon, app name). The Go binary's enrichPath()
            # discovers gh via the user's login shell PATH, so the nix
            # wrapper's PATH injection is not needed here.
            cp $out/bin/.cosmonaut-wrapped "$out/Applications/Cosmonaut.app/Contents/MacOS/cosmonaut"
          '';

          meta = with pkgs.lib; {
            description = "CLI for starting GitHub Codespaces and opening them in Zed";
            license = licenses.mit;
            mainProgram = "cosmonaut";
          };
        };
      in
      {
        packages = {
          default = cosmonaut;
          cosmonaut = cosmonaut;
        }
        # Linux: release tarball + AppImage
        // pkgs.lib.optionalAttrs pkgs.stdenv.isLinux {
          release =
            let
              pkg = cosmonaut;
              arch = if system == "x86_64-linux" then "amd64" else "arm64";
            in
            pkgs.runCommand "cosmonaut-${arch}.tar.gz"
              { nativeBuildInputs = [ pkgs.gzip ]; }
              ''
                # Ship the real Go binary (.cosmonaut-wrapped), not the nix
                # wrapper at bin/cosmonaut: that wrapper hardcodes /nix/store
                # paths and is unusable outside the build sandbox. Users need
                # gh on their own PATH, same as any standalone distribution.
                mkdir -p cosmonaut
                cp ${pkg}/bin/.cosmonaut-wrapped cosmonaut/cosmonaut
                chmod +w cosmonaut/cosmonaut
                cp ${./dist/cosmonaut.config.example.json} cosmonaut/
                cp ${./dist/cosmonaut.service} cosmonaut/
                tar -czvf $out -C . cosmonaut
              '';

          appimage = nix-appimage.lib.${system}.mkAppImage {
            program = "${cosmonaut}/bin/.cosmonaut-wrapped";
            pname = "cosmonaut";
            name = "cosmonaut-${if system == "x86_64-linux" then "x86_64" else "aarch64"}.AppImage";
          };
        };

        # The Darwin DMG is assembled by .github/workflows/release.yml
        # from the default package, not via a dedicated flake output,
        # so that the shipped binary is the raw .cosmonaut-wrapped file
        # instead of a nix wrapper referencing /nix/store paths.

        devShells.default = pkgs.mkShell {
          packages = [
            pkgs.go
            pkgs.gopls
            pkgs.gh
            pkgs.pkg-config
          ] ++ pkgs.lib.optionals pkgs.stdenv.isDarwin [
            pkgs.apple-sdk
          ] ++ pkgs.lib.optionals pkgs.stdenv.isLinux [
            pkgs.gtk3
            pkgs.libappindicator-gtk3
            pkgs.libGL
            pkgs.xorg.libX11
            pkgs.xorg.libXcursor
            pkgs.xorg.libXi
            pkgs.xorg.libXinerama
            pkgs.xorg.libXrandr
            pkgs.xorg.libXxf86vm
            pkgs.xorg.libXext
            pkgs.xorg.libXfixes
          ];
        };
      }
    );
}
