{
  description = "Codespace Zed Launcher – start/create GitHub Codespaces and open them in Zed";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    {
      homeManagerModules.default = import ./modules/home-manager.nix self;
      homeManagerModules.codespace-zed = import ./modules/home-manager.nix self;
    }
    //
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        codespace-zed = pkgs.buildGoModule {
          pname = "codespace-zed";
          version = "0.2.0";
          src = ./.;

          vendorHash = "sha256-b20qQYsg/KKpRtWPEs0WD9YaUd1hOI6yps7aZqmoA3U=";

          env.CGO_ENABLED = 1;

          nativeBuildInputs = [
            pkgs.makeWrapper
            pkgs.installShellFiles
            pkgs.pkg-config
          ] ++ pkgs.lib.optionals pkgs.stdenv.isLinux [
            pkgs.xvfb-run
          ];

          buildInputs = pkgs.lib.optionals pkgs.stdenv.isDarwin [
            pkgs.apple-sdk
          ] ++ pkgs.lib.optionals pkgs.stdenv.isLinux [
            pkgs.gtk3
            pkgs.libappindicator-gtk3
            # Fyne / GLFW dependencies
            pkgs.libGL
            pkgs.xorg.libX11
            pkgs.xorg.libXcursor
            pkgs.xorg.libXi
            pkgs.xorg.libXinerama
            pkgs.xorg.libXrandr
            pkgs.xorg.libXxf86vm
            pkgs.xorg.libXext
            pkgs.xorg.libXfixes
          ];

          postInstall = ''
            wrapProgram $out/bin/codespace-zed \
              --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.gh ]}

            # Shell completions (generated by cobra).
            # On Linux, xvfb-run is needed because golang.design/x/hotkey
            # initializes X11 on import.
            completionCmd="$out/bin/codespace-zed"
            if [[ "$(uname)" == "Linux" ]]; then
              completionCmd="xvfb-run $completionCmd"
            fi
            installShellCompletion --cmd codespace-zed \
              --bash <($completionCmd completion bash) \
              --zsh <($completionCmd completion zsh) \
              --fish <($completionCmd completion fish)

            # Dist files (example config, systemd service).
            install -Dm644 $src/dist/codespace-zed.config.example.json $out/share/codespace-zed/codespace-zed.config.example.json
            install -Dm644 $src/dist/codespace-zed.service $out/share/codespace-zed/codespace-zed.service
          '' + pkgs.lib.optionalString pkgs.stdenv.isDarwin ''
            # macOS .app bundle — gives the binary a dock icon, proper
            # app lifecycle, and allows launchd to manage it correctly.
            # Files must be real copies (not symlinks into /nix/store)
            # or Gatekeeper rejects the bundle as damaged.
            mkdir -p "$out/Applications/Codespace Zed.app/Contents/MacOS"
            mkdir -p "$out/Applications/Codespace Zed.app/Contents/Resources"
            cp $src/dist/Info.plist "$out/Applications/Codespace Zed.app/Contents/Info.plist"
            cp $src/assets/logo.icns "$out/Applications/Codespace Zed.app/Contents/Resources/icon.icns"
            # Copy the real Go binary (not the nix wrapper) into the app
            # bundle. The wrapper does exec -a which replaces the process
            # name with .codespace-zed-wrapped, breaking macOS bundle
            # identity (dock icon, app name). The Go binary's enrichPath()
            # discovers gh via the user's login shell PATH, so the nix
            # wrapper's PATH injection is not needed here.
            cp $out/bin/.codespace-zed-wrapped "$out/Applications/Codespace Zed.app/Contents/MacOS/codespace-zed"
          '';

          meta = with pkgs.lib; {
            description = "CLI for starting GitHub Codespaces and opening them in Zed";
            license = licenses.mit;
            mainProgram = "codespace-zed";
          };
        };
      in
      {
        packages = {
          default = codespace-zed;
          codespace-zed = codespace-zed;
        }
        # Linux: release tarball + AppImage
        // pkgs.lib.optionalAttrs pkgs.stdenv.isLinux {
          release =
            let
              pkg = codespace-zed;
              arch = if system == "x86_64-linux" then "amd64" else "arm64";
            in
            pkgs.runCommand "codespace-zed-${arch}.tar.gz"
              { nativeBuildInputs = [ pkgs.gzip pkgs.patchelf ]; }
              ''
                mkdir -p codespace-zed
                cp ${pkg}/bin/.codespace-zed-wrapped codespace-zed/codespace-zed
                chmod +w codespace-zed/codespace-zed
                patchelf --remove-rpath codespace-zed/codespace-zed
                cp ${./dist/codespace-zed.config.example.json} codespace-zed/
                cp ${./dist/codespace-zed.service} codespace-zed/
                tar -czvf $out -C . codespace-zed
              '';

          appimage =
            let
              pkg = codespace-zed;
              arch = if system == "x86_64-linux" then "x86_64" else "aarch64";

              appimageRuntime = pkgs.fetchurl (if system == "x86_64-linux" then {
                url = "https://github.com/AppImage/type2-runtime/releases/download/20251108/runtime-x86_64";
                hash = "sha256-L8qLRDySUQ8Ug6iD9gBhrQm0a5eLJjHIB82HOkfsJg0=";
              } else {
                url = "https://github.com/AppImage/type2-runtime/releases/download/20251108/runtime-aarch64";
                hash = "sha256-AMvfz5F8xsD/bTNH1Z4Moff0Wm3xpCig1tinhmTYdEQ=";
              });

              libDeps = with pkgs; [
                glib gtk3 libayatana-appindicator pango cairo gdk-pixbuf atk
                harfbuzz fontconfig freetype
                xorg.libX11 xorg.libXcursor xorg.libXrandr xorg.libXi
                xorg.libXext xorg.libXrender xorg.libXfixes
                xorg.libXcomposite xorg.libXdamage xorg.libxcb
                libxkbcommon wayland
              ];
              libPath = pkgs.lib.makeLibraryPath libDeps;
            in
            pkgs.runCommand "codespace-zed-${arch}.AppImage"
              { nativeBuildInputs = with pkgs; [ squashfsTools patchelf ]; }
              ''
                mkdir -p AppDir/usr/bin
                mkdir -p AppDir/usr/lib
                mkdir -p AppDir/usr/share/applications

                cp ${pkg}/bin/.codespace-zed-wrapped AppDir/usr/bin/codespace-zed
                chmod +w AppDir/usr/bin/*
                patchelf --remove-rpath AppDir/usr/bin/codespace-zed

                # Bundle shared libraries so the AppImage is self-contained.
                for dir in ${pkgs.lib.concatStringsSep " " (map (d: "${d}/lib") libDeps)}; do
                  if [ -d "$dir" ]; then
                    for so in "$dir"/*.so "$dir"/*.so.*; do
                      [ -e "$so" ] || continue
                      cp -n "$(readlink -f "$so")" "AppDir/usr/lib/$(basename "$so")" 2>/dev/null || true
                    done
                  fi
                done

                cat > AppDir/codespace-zed.desktop << 'DESKTOP'
                [Desktop Entry]
                Type=Application
                Name=codespace-zed
                Exec=codespace-zed applet
                Icon=codespace-zed
                Categories=Development;
                DESKTOP
                cp AppDir/codespace-zed.desktop AppDir/usr/share/applications/

                cat > AppDir/AppRun << 'APPRUN'
                #!/bin/bash
                set -e
                SELF=$(readlink -f "$0")
                APPDIR=''${SELF%/*}
                export LD_LIBRARY_PATH="''${APPDIR}/usr/lib:''${LD_LIBRARY_PATH}"
                export PATH="''${APPDIR}/usr/bin:''${PATH}"
                exec "''${APPDIR}/usr/bin/codespace-zed" "$@"
                APPRUN
                chmod +x AppDir/AppRun

                mksquashfs AppDir appimage.squashfs -root-owned -noappend -comp zstd -quiet -no-progress
                cat ${appimageRuntime} appimage.squashfs > $out
                chmod +x $out
              '';
        }
        // pkgs.lib.optionalAttrs pkgs.stdenv.isDarwin {
          release =
            let
              pkg = codespace-zed;
              arch = if system == "x86_64-darwin" then "amd64" else "arm64";
            in
            pkgs.runCommand "codespace-zed-darwin-${arch}.dmg"
              {
                nativeBuildInputs = [ pkgs.cctools ];
              }
              ''
                export PATH="/usr/bin:$PATH"
                mkdir -p staging
                cp -rL "${pkg}/Applications/Codespace Zed.app" staging/
                chmod -R u+w staging/

                # Rewrite any /nix/store dylib references to /usr/lib
                # so the binary works on non-Nix macOS systems.
                bin="staging/Codespace Zed.app/Contents/MacOS/codespace-zed"
                for dep in $(otool -L "$bin" | grep /nix/store | awk '{print $1}'); do
                  base=$(basename "$dep")
                  install_name_tool -change "$dep" "/usr/lib/$base" "$bin"
                done

                # Script that symlinks the CLI binary into /usr/local/bin
                # so users can run codespace-zed from the terminal.
                cat > staging/Install\ CLI.command << 'SCRIPT'
                #!/bin/bash
                set -e
                dst="/usr/local/bin/codespace-zed"
                src="/Applications/Codespace Zed.app/Contents/MacOS/codespace-zed"
                if [ ! -f "$src" ]; then
                  echo "Error: Codespace Zed.app not found in /Applications."
                  echo "Drag the app to Applications first, then run this again."
                  exit 1
                fi
                mkdir -p /usr/local/bin
                ln -sf "$src" "$dst"
                echo "Installed: $dst -> $src"
                SCRIPT
                chmod +x staging/Install\ CLI.command

                # Applications symlink for drag-and-drop install
                ln -s /Applications staging/Applications

                hdiutil create -volname "Codespace Zed" -srcfolder staging \
                  -ov -format UDZO $out
              '';
        };

        devShells.default = pkgs.mkShell {
          packages = [
            pkgs.go
            pkgs.gopls
            pkgs.gh
            pkgs.pkg-config
          ] ++ pkgs.lib.optionals pkgs.stdenv.isDarwin [
            pkgs.apple-sdk
          ] ++ pkgs.lib.optionals pkgs.stdenv.isLinux [
            pkgs.gtk3
            pkgs.libappindicator-gtk3
            pkgs.libGL
            pkgs.xorg.libX11
            pkgs.xorg.libXcursor
            pkgs.xorg.libXi
            pkgs.xorg.libXinerama
            pkgs.xorg.libXrandr
            pkgs.xorg.libXxf86vm
            pkgs.xorg.libXext
            pkgs.xorg.libXfixes
          ];
        };
      }
    );
}
